### PR TITLE
2020 Bachelor project

### PR DESCRIPTION
**Pull request by Vevn**
Working branch, shown in our demo's

### CODE REVIEW

**Comment by rartino** [comment]
Since you've made a few accidental PRs while you were collecting your changes -- is this the PR I should approve into the main branch of ENVISIoN?

**Comment by rartino** [comment]
I note that User guide and the front-page README.rst does not seem to be updated in this PR?

**Comment by rartino** [comment]
Thanks for the user guide as pdf (but we also want the updated .tex files checked into the repository.)

**Comment by Vevn** [comment]
Ive commited the source files for the user guide .tex as requested.

**Comment by rartino** [comment]
Thanks, looks good. Are you ready with this PR now? Is this the full "delivery"?

**Comment by Vevn** [comment]
This is the full working delivery, if you notice anything not up to snuff, make and issue or you can contact me directly.

**Comment by rartino** [comment]
@Vevn I did merge this now, but after doing so I realize that you haven't made any update to the main README.rst. You really should add yourselves and this years contributions to this README so they are displayed properly!

As for the rest of the content in the README, it is OK if you don't want to put in more effort. I can oversee merging back material from this year's user guide (I've meant to setup a way to handle the overlap between the user guide and README automatically anyway).

**Pull request merged**
